FROM nginx:alpine

# Copy custom configuration files
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./app /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
